In [1]:
# Importación de librerías
import pandas as pd
import numpy as np

# Configuración para visualizar todas las columnas
pd.set_option('display.max_columns', None)

1. Revisamos los archivos exportados para comprobar la integridad de los datos

In [11]:
df_empr_const = pd.read_csv('../files/data_processed/empresas_constituidas.csv')

In [12]:
df_empr_const.sample(5)

,id_const,territorio,id_tiempo,tipo,numero_sociedades,capital
3706,3707,"Rioja, La",201010,Mercantiles,31,1027000
4765,4766,"Asturias, Principado de",201403,Sociedades anónimas,1,60000
9243,9244,Canarias,202601,Sociedades de responsabilidad limitada,387,8423000
4468,4469,Aragón,202008,Sociedades anónimas,0,0
14424,14425,Cataluña,201512,S. Comanditarias y S. Colectivas,1,1000

In [13]:
df_empr_const.info()

<class 'pandas.DataFrame'>
RangeIndex: 16720 entries, 0 to 16719
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_const           16720 non-null  int64
 1   territorio         16720 non-null  str
 2   id_tiempo          16720 non-null  int64
 3   tipo               16720 non-null  str
 4   numero_sociedades  16720 non-null  int64
 5   capital            16720 non-null  int64
dtypes: int64(4), str(2)
memory usage: 783.9 KB

In [15]:
df_empr_const.describe(include='number').T

,count,mean,std,min,25%,50%,75%,max
id_const,16720.0,8.360500e+03,4.826793e+03,1.0,4180.75,8360.5,12540.25,1.672000e+04
id_tiempo,16720.0,2.016737e+05,5.294115e+02,200801.0,201207.75,201702.5,202109.25,2.026040e+05
numero_sociedades,16720.0,2.134034e+02,4.471220e+02,0.0,0.00,7.0,215.00,3.173000e+03
capital,16720.0,1.544442e+07,1.489657e+08,0.0,0.00,442000.0,7895000.00,1.259172e+10

In [16]:
df_empr_const.describe(include='string').T

            count unique          top  freq
territorio  16720     19    Andalucía   880
tipo        16720      4  Mercantiles  4180

In [34]:
df_empr_const["territorio"].unique()

<StringArray>
[                  'Andalucía',                      'Aragón',
     'Asturias, Principado de',              'Balears, Illes',
                    'Canarias',                   'Cantabria',
             'Castilla y León',        'Castilla - La Mancha',
                    'Cataluña',        'Comunitat Valenciana',
                 'Extremadura',                     'Galicia',
        'Madrid, Comunidad de',           'Murcia, Región de',
 'Navarra, Comunidad Foral de',                  'País Vasco',
                   'Rioja, La',                       'Ceuta',
                     'Melilla']
Length: 19, dtype: str

Pendiente de arreglar los nombres, minúsculas, tildes, etc. normalizar la columna

In [17]:
df_empr_const["tipo"].unique()

<StringArray>
[                           'Mercantiles',
                    'Sociedades anónimas',
 'Sociedades de responsabilidad limitada',
       'S. Comanditarias y S. Colectivas']
Length: 4, dtype: str

Tras revisar los tipos de empresa, nos damos cuenta que "Mercantiles" es un total de las empresas SL, y SA, vamos a comprobarlo.

In [ ]:
df_empr_const[df_empr_const["tipo"] == "Mercantiles"].sample(10)

,id_const,territorio,id_tiempo,tipo,numero_sociedades,capital
513,514,"Asturias, Principado de",202003,Mercantiles,68,4498000
2683,2684,"Madrid, Comunidad de",202209,Mercantiles,1708,187197000
1755,1756,Castilla - La Mancha,200805,Mercantiles,412,7204000
3971,3972,Melilla,202505,Mercantiles,10,1037000
950,951,Canarias,202006,Mercantiles,186,155088000
21,22,Andalucía,202407,Mercantiles,1564,78298000
1270,1271,Cantabria,201202,Mercantiles,67,3530000
2576,2577,Galicia,201304,Mercantiles,413,8658000
754,755,"Balears, Illes",201806,Mercantiles,290,14381000
2096,2097,Comunitat Valenciana,201608,Mercantiles,732,21413000

In [44]:
df_empr_const["tipo"].value_counts()

tipo
Mercantiles                               4180
Sociedades anónimas                       4180
Sociedades de responsabilidad limitada    4180
S. Comanditarias y S. Colectivas          4180
Name: count, dtype: int64

La razón que los valores totales coinciden es porque hay una fila por fecha, independientemente si hay disueltas o no (0)

In [33]:
df_empr_const[df_empr_const["tipo"] == "Mercantiles"].shape

(4180, 6)

In [26]:
df_empr_const[(df_empr_const["territorio"] == "Melilla") & (df_empr_const["id_tiempo"] == 202505)].head(100)

,id_const,territorio,id_tiempo,tipo,numero_sociedades,capital
3971,3972,Melilla,202505,Mercantiles,10,1037000
8151,8152,Melilla,202505,Sociedades anónimas,0,0
12331,12332,Melilla,202505,Sociedades de responsabilidad limitada,10,1037000
16511,16512,Melilla,202505,S. Comanditarias y S. Colectivas,0,0

In [ ]:
df_empr_const[(df_empr_const["territorio"] == "Canarias") & (df_empr_const["id_tiempo"] == 202006)].head(100)

,id_const,territorio,id_tiempo,tipo,numero_sociedades,capital
950,951,Canarias,202006,Mercantiles,186,155088000
5130,5131,Canarias,202006,Sociedades anónimas,0,0
9310,9311,Canarias,202006,Sociedades de responsabilidad limitada,186,155088000
13490,13491,Canarias,202006,S. Comanditarias y S. Colectivas,0,0

In [28]:
df_empr_const[(df_empr_const["territorio"] == "Andalucía") & (df_empr_const["id_tiempo"] == 202407)].head(100)

,id_const,territorio,id_tiempo,tipo,numero_sociedades,capital
21,22,Andalucía,202407,Mercantiles,1564,78298000
4201,4202,Andalucía,202407,Sociedades anónimas,2,1840000
8381,8382,Andalucía,202407,Sociedades de responsabilidad limitada,1562,76458000
12561,12562,Andalucía,202407,S. Comanditarias y S. Colectivas,0,0

Confirmamos nuestras sospechas, procederemos en el paso de transformación a eliminar esas filas. df_empr_const["tipo"] == "Mercantiles"

------------------------------------

In [35]:
df_empr_dis = pd.read_csv('../files/data_processed/empresas_disueltas.csv')

In [36]:
df_empr_dis.sample(5)

,id_dis,territorio,id_tiempo,razon,numero_sociedades
12190,12191,Ceuta,201810,Otras,0
5726,5727,Castilla - La Mancha,202510,Por fusión,3
3091,3092,"Navarra, Comunidad Foral de",202505,Voluntaria,1
6487,6488,Extremadura,201705,Por fusión,1
5101,5102,Canarias,202211,Por fusión,13

In [39]:
df_empr_dis.info()

<class 'pandas.DataFrame'>
RangeIndex: 12540 entries, 0 to 12539
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_dis             12540 non-null  int64
 1   territorio         12540 non-null  str
 2   id_tiempo          12540 non-null  int64
 3   razon              12540 non-null  str
 4   numero_sociedades  12540 non-null  int64
dtypes: int64(3), str(2)
memory usage: 490.0 KB

In [41]:
df_empr_dis.shape

(12540, 5)

In [37]:
df_empr_dis.describe(include='number').T

,count,mean,std,min,25%,50%,75%,max
id_dis,12540.0,6270.500000,3620.130523,1.0,3135.75,6270.5,9405.25,12540.0
id_tiempo,12540.0,201673.700000,529.416812,200801.0,201207.75,201702.5,202109.25,202604.0
numero_sociedades,12540.0,32.513238,71.914047,0.0,2.00,8.0,31.00,1114.0

In [38]:
df_empr_dis.describe(include='string').T

            count unique         top  freq
territorio  12540     19   Andalucía   660
razon       12540      3  Voluntaria  4180

In [43]:
df_empr_dis["razon"].value_counts()

razon
Voluntaria    4180
Por fusión    4180
Otras         4180
Name: count, dtype: int64

La razón que los valores totales coinciden es porque hay una fila por fecha, independientemente si hay disueltas o no (0)

-------------------------

In [45]:
df_ipc = pd.read_csv('../files/data_processed/ipc.csv')

In [47]:
df_ipc.sample(10)

        id_tiempo  id_territorio  id_sector  id_medida  valor_ipc
79711      202502              6         13          1     98.736
122689     200806              9          7          3     -0.200
38983      202503              4          6          2      0.400
213488     201101             15          1          1     76.077
276804     200809             18         13          1     61.952
245525     200209             16         14          2     -0.100
194254     200205             13         12          3      6.000
78682      201303              6         12          1     71.467
125707     202507              9         10          2      2.000
143946     201906             10         11          4      0.100

In [48]:
df_ipc.info()

<class 'pandas.DataFrame'>
RangeIndex: 311752 entries, 0 to 311751
Data columns (total 5 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   id_tiempo      311752 non-null  int64
 1   id_territorio  311752 non-null  int64
 2   id_sector      311752 non-null  int64
 3   id_medida      311752 non-null  int64
 4   valor_ipc      311752 non-null  float64
dtypes: float64(1), int64(4)
memory usage: 11.9 MB

In [49]:
df_ipc.describe(include='number').T

,count,mean,std,min,25%,50%,75%,max
id_tiempo,311752.0,201377.771331,705.028615,200201.0,200802.00,201403.0,202004.00000,202605.000
id_territorio,311752.0,11.000000,5.477234,2.0,6.00,11.0,16.00000,20.000
id_sector,311752.0,7.500000,4.031135,1.0,4.00,7.5,11.00000,14.000
id_medida,311752.0,2.500000,1.118036,1.0,1.75,2.5,3.25000,4.000
valor_ipc,311752.0,21.504041,37.066418,-22.4,0.10,1.5,37.37975,258.216

In [50]:
df_ipc[df_ipc["valor_ipc"] == -22.4].head()

        id_tiempo  id_territorio  id_sector  id_medida  valor_ipc
169387     202308             12          5          3      -22.4

In [55]:
df_ipc[df_ipc["valor_ipc"] <0].sample(10)

        id_tiempo  id_territorio  id_sector  id_medida  valor_ipc
264086     201808             18          2          2       -0.1
148632     201908             11          1          4       -0.3
71891      201707              6          6          2       -1.8
57865      201405              5          8          2       -0.2
11037      201001              2         10          2       -1.6
287690     200412             19          8          2       -1.6
108827     201601              8          9          4       -0.1
174099     202108             12          9          3       -2.9
295209     201303             19         14          4       -0.6
130642     200412              9         14          2       -0.1

----------------

In [56]:
df_sectores_ipc = pd.read_csv('../files/data_processed/sectores_ipc.csv')

In [57]:
df_sectores_ipc.sample(10)

    id_sector                                      nombre_sector
11         12            Restaurantes y servicios de alojamiento
7           8                                         Transporte
8           9                       Información y comunicaciones
5           6  Muebles, artículos del hogar y artículos para ...
2           3                       Bebidas alcohólicas y tabaco
1           2                 Alimentos y bebidas no alcohólicas
13         14  Cuidado personal, protección social, y bienes ...
9          10         Actividades recreativas, deporte y cultura
10         11                                          Enseñanza
0           1                                     Índice general

In [59]:
df_sectores_ipc.info()

<class 'pandas.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_sector      14 non-null     int64
 1   nombre_sector  14 non-null     str
dtypes: int64(1), str(1)
memory usage: 356.0 bytes

In [60]:
df_sectores_ipc.describe(include='number').T

           count  mean     std  min   25%  50%    75%   max
id_sector   14.0   7.5  4.1833  1.0  4.25  7.5  10.75  14.0

In [61]:
df_sectores_ipc.describe(include='string').T

              count unique             top freq
nombre_sector    14     14  Índice general    1

In [62]:
df_sectores_ipc["nombre_sector"].unique()

<StringArray>
[                                                                    'Índice general',
                                                 'Alimentos y bebidas no alcohólicas',
                                                       'Bebidas alcohólicas y tabaco',
                                                                  'Vestido y calzado',
                             'Vivienda, agua, electricidad, gas y otros combustibles',
 'Muebles, artículos del hogar y artículos para el mantenimiento corriente del hogar',
                                                                            'Sanidad',
                                                                         'Transporte',
                                                       'Información y comunicaciones',
                                         'Actividades recreativas, deporte y cultura',
                                                                          'Enseñanza',
                                            'Restaurantes y servicios de alojamiento',
                                                    'Seguros y servicios financieros',
                 'Cuidado personal, protección social, y bienes y servicios diversos']
Length: 14, dtype: str

------------------

In [63]:
df_territorio = pd.read_csv('../files/data_processed/territorio.csv')

In [64]:
df_territorio.sample(10)

    id_territorio            nombre_territorio
8               9         Castilla - La Mancha
4               5               Balears, Illes
5               6                     Canarias
13             14         Madrid, Comunidad de
14             15            Murcia, Región de
2               3                       Aragón
18             19                        Ceuta
6               7                    Cantabria
0               1                     Nacional
15             16  Navarra, Comunidad Foral de

In [65]:
df_territorio.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 2 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_territorio      20 non-null     int64
 1   nombre_territorio  20 non-null     str
dtypes: int64(1), str(1)
memory usage: 452.0 bytes

In [ ]:
df_territorio.describe(include='string').T

                  count unique       top freq
nombre_territorio    20     20  Nacional    1

In [68]:
df_territorio["nombre_territorio"].unique()

<StringArray>
[                   'Nacional',                   'Andalucía',
                      'Aragón',     'Asturias, Principado de',
              'Balears, Illes',                    'Canarias',
                   'Cantabria',             'Castilla y León',
        'Castilla - La Mancha',                    'Cataluña',
        'Comunitat Valenciana',                 'Extremadura',
                     'Galicia',        'Madrid, Comunidad de',
           'Murcia, Región de', 'Navarra, Comunidad Foral de',
                  'País Vasco',                   'Rioja, La',
                       'Ceuta',                     'Melilla']
Length: 20, dtype: str

-----------------

In [69]:
df_tiempo = pd.read_csv('../files/data_processed/tiempo.csv')

In [70]:
df_tiempo.sample(10)

     id_tiempo  anio  mes nombre_mes
102     201711  2017   11  Noviembre
7       202510  2025   10    Octubre
110     201703  2017    3      Marzo
275     200306  2003    6      Junio
237     200608  2006    8     Agosto
277     200304  2003    4      Abril
58      202107  2021    7      Julio
211     200810  2008   10    Octubre
282     200211  2002   11  Noviembre
131     201506  2015    6      Junio

In [71]:
df_tiempo.info()

<class 'pandas.DataFrame'>
RangeIndex: 293 entries, 0 to 292
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id_tiempo   293 non-null    int64
 1   anio        293 non-null    int64
 2   mes         293 non-null    int64
 3   nombre_mes  293 non-null    str
dtypes: int64(3), str(1)
memory usage: 9.3 KB

In [72]:
df_tiempo.describe(include='number').T

,count,mean,std,min,25%,50%,75%,max
id_tiempo,293.0,201377.771331,706.233691,200201.0,200802.0,201403.0,202004.0,202605.0
anio,293.0,2013.713311,7.063295,2002.0,2008.0,2014.0,2020.0,2026.0
mes,293.0,6.440273,3.463214,1.0,3.0,6.0,9.0,12.0

---------------------

In [73]:
df_tipo_medida = pd.read_csv('../files/data_processed/tipo_medida.csv')

In [75]:
df_tipo_medida.head(10)

   id_medida                  nombre_medida
0          1                         Índice
1          2              Variación mensual
2          3                Variación anual
3          4  Variación en lo que va de año

In [76]:
df_tipo_medida.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_medida      4 non-null      int64
 1   nombre_medida  4 non-null      str
dtypes: int64(1), str(1)
memory usage: 196.0 bytes

In [78]:
df_tipo_medida.value_counts()

id_medida  nombre_medida
1          Índice                           1
2          Variación mensual                1
3          Variación anual                  1
4          Variación en lo que va de año    1
Name: count, dtype: int64